[project]
authors = ["Jack Myers <jack.myers@intel.com>"]
channels = ["https://software.repos.intel.com/python/conda/", "conda-forge"]
description = "Add a short description here"
name = "tabby"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
install-tabby = "bash scripts/install-tabby.sh"
install-localai = "bash scripts/install-localai.sh"

[dependencies]
wget = ">=1.21.4,<2"
unzip = ">=6.0,<7"
cmake = ">=3.30.5,<4"
c-compiler = ">=1.8.0,<2"
cxx-compiler = ">=1.8.0,<2"
go = ">=1.23.3,<2"
make = ">=4.4.1,<5"
protobuf-c = ">=1.5.0,<2"
protoc-gen-go = ">=1.5.3,<2"
google-api-core-grpc = ">=2.22.0,<3"
dpcpp_linux-64 = ">=2025.0.0,<2026"
onednn-devel = ">=2025.0.0,<2026"
mkl-devel = ">=2025.0.0,<2026"
mkl-devel-dpcpp = ">=2025.0.0,<2026"
onemkl-sycl-blas = ">=2025.0.0,<2026"
mkl-static = ">=2025.0.0,<2026"
onemkl-sycl-lapack = ">=2025.0.0,<2026"
onemkl-sycl-dft = ">=2025.0.0,<2026"
onemkl-sycl-sparse = ">=2025.0.0,<2026"
onemkl-sycl-vm = ">=2025.0.0,<2026"
onemkl-sycl-datafitting = ">=2025.0.0,<2026"
tbb-devel = ">=2022.0.0,<2023"
dal-devel = ">=2025.0.0,<2026"
dal-static = ">=2025.0.0,<2026"
oneccl-devel = ">=2021.14.0,<2022"

[activation]
scripts = [ "env.sh" ]
