# Completion model
[model.completion.http]
kind = "ollama/completion"
model_name = "deepseek-coder-v2"
api_endpoint = "http://localhost:11434"
prompt_template = "<｜fim▁begin｜>{prefix}<｜fim▁hole｜>{suffix}<｜fim▁end｜>" # Example prompt template for the CodeLlama model series.

[completion]
# Maximum length of the input prompt, in UTF-8 characters. The default value is set to 1536.
max_input_length = 15000

# Maximum number of decoding tokens. The default value is set to 64.
max_decoding_tokens = 1024
