# Completion model
[model.completion.http]
kind = "ollama/completion"
model_name = "deepseek-coder-v2:lite"
api_endpoint = "http://localhost:11434"
prompt_template = "<｜fim▁begin｜>{prefix}\n<｜fim▁hole｜>\n{suffix}<｜fim▁end｜>" # Example prompt template for the CodeLlama model series.
