version = 1

[envs.rattler-build]
channels = ["conda-forge"]
dependencies = { rattler-build = "*" }
exposed = { rattler-build = "rattler-build" }

[envs.anaconda-client]
channels = ["conda-forge"]
dependencies = { anaconda-client = "*" }
exposed = { anaconda = "anaconda", binstar = "binstar", conda-server = "conda-server" }

[envs.shell-tools]
channels = ["conda-forge/label/rust_dev", "conda-forge"]
dependencies = { python = "*", git = "*", cmake = "*", make = "*", ninja = "*", nodejs = "*", ripgrep = "*", tree-sitter-cli = "*", bottom = "*", lazygit = "*", gdu = "*", neocmakelsp = "*", mdformat = "*", fzf = "*", gcc = "*", gxx = "*", openssl = "*", zlib = "*", zstd = "*", pkg-config = "*", rust = "*", go = "*", nushell = "*" }
exposed = { nu = "nu", bash = "bash" }
