return {
  --   -- AI Code Completion
  --   {
  --     'zbirenbaum/copilot.lua',
  --     cmd = 'Copilot',
  --     event = 'InsertEnter',
  --     opts = {
  --       suggestion = { enabled = false },
  --       panel = { enabled = false },
  --       filetypes = {
  --         markdown = true,
  --         help = true,
  --       },
  --       lsp_binary = 'copilot-language-server',
  --     },
  --   },
  --   {
  --     'saghen/blink.cmp',
  --     dependencies = {
  --       'zbirenbaum/copilot.lua',
  --       'fang2hou/blink-copilot', -- Copilot integration
  --     },
  --     opts = {
  --       sources = {
  --         default = { 'copilot' },
  --         providers = {
  --           copilot = {
  --             name = 'copilot',
  --             module = 'blink-copilot',
  --             score_offset = 100,
  --             async = true,
  --             opts = {
  --               max_completions = 3,
  --               max_attempts = 4,
  --               kind_name = 'Copilot',
  --               kind_icon = ' ',
  --               kind_hl = false,
  --               debounce = 200,
  --               auto_refresh = {
  --                 backward = true,
  --                 forward = true,
  --               },
  --             },
  --           },
  --         },
  --       },
  --     },
  --     opts_extend = {
  --       'sources.default',
  --       'sources.providers',
  --     },
  --   },
}
